name: "FTP directory scan"
description: "Scans an FTP directory and stores all file names in a .json file."
author: "Tobias Linz"
inputs:
  server: 
    required: true
    description: "ftp server"
  user:
    required: true
    description: "ftp username"
  password:
    required: true
    description: "ftp password"
  port:
    required: false
    description: "Server port to connect to"
    default: "21"
  secure:
    required: false
    description: "True: ftps - False: ftp"
    default: true
  timeout:
    required: false
    description: "Timeout in milliseconds that will be used for any connection made"
    default: 30000
  verbose: 
    required: false
    description: "If you encounter a problem, it may help to log out all communication"
    default: false
  server-dir:
    required: true
    description: "Path to scan on the server. Must end with trailing slash /"
runs: 
  using: "node20"
  main: "dist/index.js"
branding: 
  icon: "folder"
  color: "blue"
